[package]
name = "avro-schema-derive"
version = "0.1.0"
authors = ["Brian Merchant <bhmerchant@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.31", features = ["extra-traits"] }
quote = "1.0.7"
proc-macro2 = "1.0.19"
avro-rs = { path = "../avro-rs", features = ["schematize"] }
#avro-rs = { git = "https://github.com/bzm3r/avro-rs.git", branch = "master"}
